import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'royal-red-anarkali',
    name: 'Royal Red Anarkali',
    description: 'A stunning red georgette anarkali with intricate zari work, perfect for weddings.',
    price: '₹14,999',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'midnight-blue-lehenga',
    name: 'Midnight Blue Lehenga',
    description: 'A beautiful lehenga in midnight blue velvet with silver embroidery.',
    price: '₹18,500',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'golden-sunset-saree',
    name: 'Golden Sunset Saree',
    description: 'An elegant chiffon saree in shades of orange and gold, with a matching blouse piece.',
    price: '₹11,200',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'emerald-green-sharara',
    name: 'Emerald Green Sharara',
    description: 'A vibrant emerald green sharara set in silk with gota patti work.',
    price: '₹9,800',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'pastel-peach-kurta',
    name: 'Pastel Peach Kurta Set',
    description: 'A soothing pastel peach cotton kurta with palazzos, ideal for daytime events.',
    price: '₹6,500',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'classic-black-saree',
    name: 'Classic Black Saree',
    description: 'A timeless black satin saree with a minimalist border for a sophisticated look.',
    price: '₹8,999',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'lavender-garden-lehenga',
    name: 'Lavender Garden Lehenga',
    description: 'A dreamy lavender lehenga with floral prints and a net dupatta.',
    price: '₹13,000',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'ivory-pearl-anarkali',
    name: 'Ivory Pearl Anarkali',
    description: 'An off-white anarkali adorned with delicate pearls and threadwork.',
    price: '₹16,800',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'mustard-yellow-salwar',
    name: 'Mustard Yellow Salwar',
    description: 'A bright and cheerful mustard yellow salwar kameez in chanderi fabric.',
    price: '₹7,250',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'rose-gold-gown',
    name: 'Rose Gold Gown',
    description: 'An exquisite rose gold evening gown with sequin embellishments.',
    price: '₹22,000',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'teal-blue-kurta',
    name: 'Teal Blue Kurta',
    description: 'A smart teal blue straight-fit kurta with cigarette pants.',
    price: '₹5,900',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'fuchsia-pink-saree',
    name: 'Fuchsia Pink Saree',
    description: 'A bold and beautiful fuchsia pink silk saree with a contrasting blouse.',
    price: '₹10,500',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'maroon-velvet-lehenga',
    name: 'Maroon Velvet Lehenga',
    description: 'A rich maroon velvet lehenga, perfect for winter weddings.',
    price: '₹19,999',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'sea-green-churidar',
    name: 'Sea Green Churidar Suit',
    description: 'A refreshing sea green suit with a floral dupatta.',
    price: '₹8,100',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'crimson-red-kurta-set',
    name: 'Crimson Red Kurta Set',
    description: 'A simple yet elegant crimson red kurta with straight pants.',
    price: '₹6,850',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
];
