import type { Product } from './types';

export const products: Product[] = [
  {
    id: 'anarkali-dream',
    name: 'Anarkali Dream',
    description: 'A flowing anarkali suit in pastel hues, perfect for festive occasions.',
    price: '₹7,999',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'blush-lehenga',
    name: 'Blush Pink Lehenga',
    description: 'Intricately embroidered lehenga choli with a modern silhouette.',
    price: '₹12,499',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'ivory-saree',
    name: 'Ivory & Gold Saree',
    description: 'An elegant organza saree with delicate gold threadwork.',
    price: '₹9,899',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'velvet-kurta',
    name: 'Velvet Sharara Set',
    description: 'A rich velvet kurta paired with a flowing sharara.',
    price: '₹8,500',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'floral-kurti',
    name: 'Floral Print Kurti',
    description: 'A comfortable and chic floral kurti for everyday elegance.',
    price: '₹4,200',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'silk-salwar',
    name: 'Silk Salwar Kameez',
    description: 'Classic silk salwar kameez with a contemporary twist.',
    price: '₹6,750',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'stitched',
  },
  {
    id: 'chanderi-silk',
    name: 'Chanderi Silk Suit',
    description: 'Unstitched Chanderi silk fabric for a custom-fit suit.',
    price: '₹3,500',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'unstitched',
  },
  {
    id: 'banarasi-fabric',
    name: 'Banarasi Brocade Fabric',
    description: 'Luxurious Banarasi brocade for creating your own masterpiece.',
    price: '₹4,800',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'unstitched',
  },
  {
    id: 'cotton-print',
    name: 'Jaipuri Cotton Print',
    description: 'Vibrant and breathable Jaipuri cotton for casual wear.',
    price: '₹2,200',
    imageUrl: 'https://placehold.co/600x800.png',
    category: 'unstitched',
  },
];
